version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./config
    networks:
      - custom_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 3

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./config
    networks:
      - custom_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # Cloudflare Tunnel - Exposes HDFS WebHDFS publicly
  # ============================================
  # Option 1: Quick Tunnel for NameNode (No auth, temporary URL)
  # Use this for testing - gives you a *.trycloudflare.com URL
  cloudflared-namenode:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-hdfs-namenode
    restart: unless-stopped
    command: tunnel --url http://namenode:9870
    networks:
      - custom_network
    depends_on:
      namenode:
        condition: service_healthy
    profiles:
      - quick-tunnel

  # Quick Tunnel for DataNode (required for file read/write operations)
  cloudflared-datanode:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-hdfs-datanode
    restart: unless-stopped
    command: tunnel --url http://datanode:9864
    networks:
      - custom_network
    depends_on:
      datanode:
        condition: service_healthy
    profiles:
      - quick-tunnel

  # Option 2: Named Tunnel (Persistent URL with your domain)
  # Requires: cloudflared tunnel login && cloudflared tunnel create hdfs-tunnel
  # Then copy credentials to ./cloudflared/ folder
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-hdfs
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    networks:
      - custom_network
    depends_on:
      namenode:
        condition: service_healthy
    profiles:
      - named-tunnel

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  custom_network:
    external: true
