version: "3"

services:
  spark:
    image: apache/spark:3.5.0
    container_name: spark-spark-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - '8081:8080'
      - '7077:7077'
    networks:
      - custom_network

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-spark-1:7077
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark
    networks:
      - custom_network

networks:
  custom_network:
    external: true
